-- ============================================
-- BILLBOARD - SEED DATA
-- ============================================

INSERT INTO public.billboards (
    title,
    description,
    type,
    location,
    latitude,
    longitude,
    city,
    country,
    width,
    height,
    price,
    currency,
    pricing_period,
    lighting,
    status
)
VALUES

(
    'Madhapur Main Road Billboard',
    'High-visibility billboard in a busy commercial area.',
    'static',
    'Madhapur',
    17.4483,
    78.3915,
    'Hyderabad',
    'India',
    20,
    10,
    150000,
    'INR',
    'month',
    'backlit',
    'published'
),

(
    'HITEC City Junction Billboard',
    'Premium billboard near major IT offices.',
    'digital',
    'HITEC City',
    17.4435,
    78.3772,
    'Hyderabad',
    'India',
    30,
    12,
    200000,
    'INR',
    'month',
    'backlit',
    'published'
),

(
    'Gachibowli Main Road Billboard',
    'Large roadside advertising space with strong traffic.',
    'static',
    'Gachibowli',
    17.4401,
    78.3489,
    'Hyderabad',
    'India',
    25,
    12,
    175000,
    'INR',
    'month',
    'frontlit',
    'published'
),

(
    'Financial District Billboard',
    'Premium advertising location in Hyderabad financial district.',
    'digital',
    'Financial District',
    17.4212,
    78.3446,
    'Hyderabad',
    'India',
    30,
    15,
    250000,
    'INR',
    'month',
    'backlit',
    'published'
),

(
    'Kondapur Junction Billboard',
    'Busy commercial-road billboard.',
    'static',
    'Kondapur',
    17.4840,
    78.3915,
    'Hyderabad',
    'India',
    20,
    10,
    125000,
    'INR',
    'month',
    'frontlit',
    'published'
),

(
    'Kukatpally Highway Billboard',
    'High-traffic billboard near major residential and commercial areas.',
    'static',
    'Kukatpally',
    17.4849,
    78.4138,
    'Hyderabad',
    'India',
    25,
    10,
    140000,
    'INR',
    'month',
    'backlit',
    'published'
),

(
    'Banjara Hills Premium Billboard',
    'Premium advertising space in a high-value neighborhood.',
    'static',
    'Banjara Hills',
    17.4156,
    78.4347,
    'Hyderabad',
    'India',
    20,
    10,
    180000,
    'INR',
    'month',
    'backlit',
    'published'
),

(
    'Jubilee Hills Road Billboard',
    'High-visibility billboard near commercial and entertainment areas.',
    'digital',
    'Jubilee Hills',
    17.4326,
    78.4071,
    'Hyderabad',
    'India',
    25,
    12,
    225000,
    'INR',
    'month',
    'backlit',
    'published'
),

(
    'LB Nagar Junction Billboard',
    'Large billboard near a busy transportation junction.',
    'static',
    'LB Nagar',
    17.3457,
    78.5522,
    'Hyderabad',
    'India',
    20,
    10,
    110000,
    'INR',
    'month',
    'frontlit',
    'published'
),

(
    'Ameerpet Main Road Billboard',
    'Advertising space in a highly active commercial zone.',
    'static',
    'Ameerpet',
    17.4375,
    78.4483,
    'Hyderabad',
    'India',
    15,
    10,
    100000,
    'INR',
    'month',
    'frontlit',
    'published'
),

(
    'Begumpet Airport Road Billboard',
    'High-traffic billboard along a major city road.',
    'static',
    'Begumpet',
    17.4447,
    78.4662,
    'Hyderabad',
    'India',
    20,
    10,
    135000,
    'INR',
    'month',
    'backlit',
    'published'
),

(
    'Uppal Main Road Billboard',
    'Roadside billboard serving a large residential population.',
    'static',
    'Uppal',
    17.4058,
    78.5591,
    'Hyderabad',
    'India',
    20,
    10,
    95000,
    'INR',
    'month',
    'frontlit',
    'published'
),

(
    'Secunderabad Junction Billboard',
    'Busy billboard location near major transport routes.',
    'static',
    'Secunderabad',
    17.4399,
    78.4983,
    'Hyderabad',
    'India',
    25,
    10,
    120000,
    'INR',
    'month',
    'backlit',
    'published'
),

(
    'Mehdipatnam Main Road Billboard',
    'Roadside advertising space with consistent traffic.',
    'static',
    'Mehdipatnam',
    17.3954,
    78.4383,
    'Hyderabad',
    'India',
    15,
    10,
    90000,
    'INR',
    'month',
    'frontlit',
    'published'
),

(
    'Panjagutta Junction Billboard',
    'Premium billboard near a major commercial junction.',
    'digital',
    'Panjagutta',
    17.4255,
    78.4505,
    'Hyderabad',
    'India',
    25,
    12,
    190000,
    'INR',
    'month',
    'backlit',
    'published'
),

(
    'Moosapet Road Billboard',
    'Roadside billboard in a busy industrial and residential area.',
    'static',
    'Moosapet',
    17.4617,
    78.4284,
    'Hyderabad',
    'India',
    20,
    10,
    85000,
    'INR',
    'month',
    'frontlit',
    'published'
),

(
    'Shamshabad Airport Road Billboard',
    'Large-format advertising space near the airport route.',
    'static',
    'Shamshabad',
    17.2403,
    78.4294,
    'Hyderabad',
    'India',
    30,
    12,
    160000,
    'INR',
    'month',
    'backlit',
    'published'
),

(
    'Abids Commercial Billboard',
    'Central-city billboard in a busy commercial district.',
    'static',
    'Abids',
    17.3930,
    78.4744,
    'Hyderabad',
    'India',
    20,
    10,
    115000,
    'INR',
    'month',
    'frontlit',
    'published'
),

(
    'Nanakramguda Billboard',
    'Premium advertising space near the Financial District.',
    'digital',
    'Nanakramguda',
    17.4140,
    78.3390,
    'Hyderabad',
    'India',
    25,
    12,
    210000,
    'INR',
    'month',
    'backlit',
    'published'
),

(
    'Miyapur Main Road Billboard',
    'High-traffic roadside billboard serving a large residential area.',
    'static',
    'Miyapur',
    17.4969,
    78.3498,
    'Hyderabad',
    'India',
    20,
    10,
    100000,
    'INR',
    'month',
    'frontlit',
    'published'
);

-- ============================================
-- END OF SEED DATA
-- ============================================